#!/usr/bin/env bash
# Extract the headless conversation and markdown bundles from the harness
# image into the frontend tree.
#
# The bundles are COMMITTED rather than produced during the frontend build: the
# frontend image installs npm packages and has no access to the dsh workspace,
# and the dev frontend is a bind mount of this tree. A committed artifact can
# be stale, so each file carries the sha it was built from and dsh-pin-gate.py
# fails when that sha is not the one the image runs.
#
# Runs where Docker runs (gray), never on the dev host.
set -euo pipefail

cd "$(dirname "$0")/../.."

SHA=$(sed -n 's/^ARG DSH_SHA=\([0-9a-f]\{40\}\)$/\1/p' harness-driver/Dockerfile)
[ -n "$SHA" ] || { echo "harness-driver/Dockerfile: no ARG DSH_SHA line"; exit 1; }

mkdir -p frontend/src/dsh
TMP=$(mktemp -d)
trap 'rm -rf "$TMP"' EXIT

docker compose build harness
docker compose run --rm --no-deps harness \
  cat /dsh/lore-conversation/dist/lore-conversation.js > "$TMP/lore-conversation.js"
docker compose run --rm --no-deps harness \
  cat /dsh/lore-conversation/dist/lore-markdown.js > "$TMP/lore-markdown.js"
docker compose run --rm --no-deps harness \
  cat /dsh/lore-conversation/dist/lore-markdown.css > "$TMP/lore-markdown.css"

# Before the banners go on: an empty dist artifact must fail, not ship as a
# banner-only file.
for PART in lore-conversation.js lore-markdown.js lore-markdown.css; do
  [ -s "$TMP/$PART" ] || { echo "the harness image produced no $PART"; exit 1; }
done

{
  echo "// GENERATED by harness-driver/conversation/sync-bundle.sh — do not edit."
  echo "// dsh-sha: $SHA"
  cat "$TMP/lore-conversation.js"
} > frontend/src/dsh/lore-conversation.js

{
  echo "// GENERATED by harness-driver/conversation/sync-bundle.sh — do not edit."
  echo "// dsh-sha: $SHA"
  cat "$TMP/lore-markdown.js"
} > frontend/src/dsh/lore-markdown.js

{
  echo "/* GENERATED by harness-driver/conversation/sync-bundle.sh — do not edit. */"
  echo "/* dsh-sha: $SHA */"
  cat "$TMP/lore-markdown.css"
} > frontend/src/dsh/lore-markdown.css

echo "wrote 3 bundles at dsh $SHA:"
wc -c frontend/src/dsh/lore-conversation.js frontend/src/dsh/lore-markdown.js frontend/src/dsh/lore-markdown.css
